### ISSUE TITLE
Continue talking

### ISSUE THREAD

**Issue by yusancky** [gamertech1/hello#3]

**Comment by yusancky** [comment]
@gamertech1

**Comment by yusancky** [comment]
Oh, I used a library by myself. Its `int` is different because it was made with `string` in C++. Then the `00` is not equal to `0` in my library. 

For example, if you input $4$. My program works like this. 

| $i$ | $n$ | $bit$ | $ans$ | string $ans$ with the library |
| :---: | :----: | :---: | :---: | :---: |
| $\text{begin}$ | $4$ | $0$ | $0$ | $\texttt{}$ |
| $1$ | $2$ | $0$ | $0$ | $\texttt{0}$ |
| $2$ | $1$ | $0$ | $0$ | $\texttt{00}$ |
| $3$ | $0$ | $0$ | $0$ | $\texttt{001}$ |

**Comment by gamertech1** [comment]
How much you know about c++

**Comment by gamertech1** [comment]
I just start learning C++ from 1st August

**Comment by gamertech1** [comment]
But  6 month I learned C++ and don't revised anything Now I have to start again

**Comment by yusancky** [comment]
Ha. I'm an C++ OIer in China although I am not good at using some algorithms. ୧⍢⃝୨

**Comment by yusancky** [comment]
And I saw you use LeetCode. $\text{(๑╹ヮ╹๑)ﾉ}$

I use CodeForces, AtCoder, Luogu and HydroOJ. $\text{ꉂ(ˊᗜˋ*)}$

**Comment by gamertech1** [comment]
Oler meaning ?

**Comment by yusancky** [comment]
Olympiad in Informatics, or OI, is among five major high school academic competitions. Since 1989, a national training team for International Olympiad in Informatics, or IOI, will be selected each year.

**Comment by yusancky** [comment]
> Oler meaning ?

Olympiad in Informatics, or OI, is among five major high school academic competitions.

**Comment by gamertech1** [comment]
thats nice

**Comment by yusancky** [comment]
I close the issue with this comment. Wish you can have a good Sunday. 

If you want to contact me on other issues, just `@yusancky `.
